# 環境設定

## 安裝 PyTorch

In [1]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-m

## 檢查 PyTorch 是否安裝成功

In [2]:
import torch

print(torch.__version__)

2.2.1+cu121


## 檢查 GPU 是否可用

In [3]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  print("Using GPU")
else:
  device = torch.device("cpu")
  print("Using CPU")

Using GPU


# 張量建立（Tensors Creation）

## 建立一般張量

In [ ]:
print(torch.Tensor([2.]))

tensor([2.])


In [ ]:
# 強制建立 32 bits 之浮點數張量
tensor_1D = torch.Tensor([1, 2, 3])
print("Tensor 1D:", tensor_1D)
print(tensor_1D.type())

tensor_2D = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print("Tensor 2D:", tensor_2D)
print(tensor_2D.type())

Tensor 1D: tensor([1., 2., 3.])
torch.FloatTensor
Tensor 2D: tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.FloatTensor


In [ ]:
# 依照傳入數據的資料型態，建立對應的張量
tensor_1D = torch.tensor([1, 2, 3])
print("Tensor 1D:", tensor_1D)
print(tensor_1D.type())

tensor_2D = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Tensor 2D:", tensor_2D)
print(tensor_2D.type())

Tensor 1D: tensor([1, 2, 3])
torch.LongTensor
Tensor 2D: tensor([[1, 2, 3],
        [4, 5, 6]])
torch.LongTensor


In [ ]:
# 用 dtype= 屬性，指定建立的張量資料型態
tensor_1D = torch.tensor([1, 2, 3], dtype=torch.float)
print("Tensor 1D:", tensor_1D)
print(tensor_1D.type())

Tensor 1D: tensor([1., 2., 3.])
torch.FloatTensor


## 建立特殊張量

In [ ]:
# 零張量
zero_1D = torch.zeros((3,))
print("Zero 1D:", zero_1D)

zero_2D = torch.zeros((2, 3))
print("Zero 2D:", zero_2D)

Zero 1D: tensor([0., 0., 0.])
Zero 2D: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 單位張量
identity_1D = torch.eye(1)
print("Identity 1D:", identity_1D)

identity_2D = torch.eye(2)
print("Identity 2D:", identity_2D)

Identity 1D: tensor([[1.]])
Identity 2D: tensor([[1., 0.],
        [0., 1.]])


In [ ]:
# 全為 1 的張量
ones_1D = torch.ones((3,))
print("Ones 1D:", ones_1D)

ones_2D = torch.ones((2, 3))
print("Ones 2D:", ones_2D)

Ones 1D: tensor([1., 1., 1.])
Ones 2D: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# 全為特定數字的張量
full_1D = torch.full((3,), 7)
print("Full 1D:", full_1D)

full_2D = torch.full((2, 3), 7)
print("Full 2D:", full_2D)

Full 1D: tensor([7, 7, 7])
Full 2D: tensor([[7, 7, 7],
        [7, 7, 7]])


## 與其它資料結構轉換

In [ ]:
# Python List 轉 Tensors
list_1D = [1, 2, 3]
tensor_1D = torch.tensor(list_1D)
print("Tensor 1D:", tensor_1D)

# Tensors 轉 Python List
list_1D = tensor_1D.tolist()
print("List 1D:", list_1D)

Tensor 1D: tensor([1, 2, 3])
List 1D: [1, 2, 3]


In [ ]:
# NumPy NDArray 轉 Tensors
import numpy as np

ndarray_1D = np.array([1, 2, 3])
tensor_1D = torch.from_numpy(ndarray_1D)
print("Tensor 1D:", tensor_1D)

# Tensors 轉 NumPy NDArray
ndarray_1D = tensor_1D.numpy()
print("NDArray 1D:", ndarray_1D)

Tensor 1D: tensor([1, 2, 3])
NDArray 1D: [1 2 3]


## 將張量在 CPU 與 GPU 間互轉

In [ ]:
# 建立一個 Tensor
tensor_1D = torch.tensor([1, 2, 3])
print("Tensor 1D:", tensor_1D)
print(tensor_1D.type())

# 將張量由 CPU 轉到 GPU 去
tensor_1D_GPU = tensor_1D.to(device)
print("Tensor 1D GPU:", tensor_1D_GPU)
print(tensor_1D_GPU.type())

# 將張量由 GPU 轉到 CPU 去
tensor_1D_CPU = tensor_1D_GPU.to(torch.device("cpu"))
print("Tensor 1D CPU:", tensor_1D_CPU)
print(tensor_1D_CPU.type())

Tensor 1D: tensor([1, 2, 3])
torch.LongTensor
Tensor 1D GPU: tensor([1, 2, 3])
torch.LongTensor
Tensor 1D CPU: tensor([1, 2, 3])
torch.LongTensor


# 張量本身資訊之取得

In [ ]:
# 取得一個張量的「軸數」
tensor_2D = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Tensor 2D:", tensor_2D)
print("Axes:", tensor_2D.dim())

# 取得一個張量的「維度/形狀」
print("Shape:", tensor_2D.shape)
print("Size:", tensor_2D.size())

# 取得一個張量的「元素數」
print("Number of Elements:", tensor_2D.numel())

# 取得一個張量的「資料型態」
print("Data Type:", tensor_2D.dtype)

Tensor 2D: tensor([[1, 2, 3],
        [4, 5, 6]])
Axes: 2
Shape: torch.Size([2, 3])
Size: torch.Size([2, 3])
Number of Elements: 6
Data Type: torch.int64


# 張量元素的讀寫

## 張量底層儲存原理

In [ ]:
# 建造一個 2x3 的張量
tensor_2D = torch.tensor([[4.0, 1.0, 5.0], [3.0, 2.0, 1.0]])
print("Tensor 2D:", tensor_2D)

# 將張量的 storage 印出
print("Storage:", tensor_2D.storage())

# 以 view 重塑為 3x2 張量
tensor_3x2 = tensor_2D.view(3, 2)
print("Tensor 3x2:", tensor_3x2)

Tensor 2D: tensor([[4., 1., 5.],
        [3., 2., 1.]])
Storage:  4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
Tensor 3x2: tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


<ipython-input-17-197ed1588d8e>:6: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print("Storage:", tensor_2D.storage())


## 張量的讀寫

In [ ]:
# 建造一個 2x3 的張量
tensor_2D = torch.tensor([[4.0, 1.0, 5.0], [3.0, 2.0, 1.0]])
print("Tensor 2D:", tensor_2D)

# 讀取位於索引值 (1, 2) 的元素
print("Element at (1, 2):", tensor_2D[1, 2])

# 將索引值 (0, 0) 的元素寫入為 9.0
tensor_2D[0, 0] = 9.0
print("Tensor 2D:", tensor_2D)

Tensor 2D: tensor([[4., 1., 5.],
        [3., 2., 1.]])
Element at (1, 2): tensor(1.)
Tensor 2D: tensor([[9., 1., 5.],
        [3., 2., 1.]])


# 張量樣本點的產生

## 線性樣本點

In [ ]:
# 產生一維線性張量樣本點
sample_1D = torch.arange(0.0, 5.0, 0.2)
print("Sample 1D:", sample_1D)

Sample 1D: tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000])


In [ ]:
# 將一維線性樣本點洗牌
index_num = sample_1D.size(0) # 第 0 軸元素個數
index_rand = torch.randperm(index_num) # 產生 index_num 個索引值亂數
sample_1D = sample_1D[index_rand]
print("Sample 1D:", sample_1D)

Sample 1D: tensor([1.2000, 0.6000, 1.0000, 3.4000, 2.4000, 2.6000, 1.4000, 0.4000, 0.8000,
        2.2000, 1.6000, 1.8000, 3.8000, 4.0000, 4.6000, 2.8000, 0.2000, 0.0000,
        4.2000, 4.4000, 3.6000, 4.8000, 3.0000, 2.0000, 3.2000])


In [ ]:
# 更改一維線性樣本點維度
sample_2D = sample_1D.view(5, 5)
print("Sample 2D:", sample_2D)

Sample 2D: tensor([[1.2000, 0.6000, 1.0000, 3.4000, 2.4000],
        [2.6000, 1.4000, 0.4000, 0.8000, 2.2000],
        [1.6000, 1.8000, 3.8000, 4.0000, 4.6000],
        [2.8000, 0.2000, 0.0000, 4.2000, 4.4000],
        [3.6000, 4.8000, 3.0000, 2.0000, 3.2000]])


In [ ]:
# 更改樣本點資料型態
sample_2D = sample_2D.type(torch.int32)
print("Sample 2D:", sample_2D)

Sample 2D: tensor([[1, 0, 1, 3, 2],
        [2, 1, 0, 0, 2],
        [1, 1, 3, 4, 4],
        [2, 0, 0, 4, 4],
        [3, 4, 3, 2, 3]], dtype=torch.int32)


## 等差樣本點

In [ ]:
# 產生等差樣本點
sample_1D = torch.linspace(0.0, 5.0, 5)
print("Sample 1D:", sample_1D)

Sample 1D: tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000])


## 等比樣本點

In [ ]:
# 產生等比樣本點
sample_1D = torch.logspace(0.0, 5.0, 5)
print("Sample 1D:", sample_1D)

Sample 1D: tensor([1.0000e+00, 1.7783e+01, 3.1623e+02, 5.6234e+03, 1.0000e+05])


## 亂數樣本點

In [ ]:
# 產生整數亂數樣本點
sample_1D = torch.randint(1, 7, size=(15,))
print("Sample 1D:", sample_1D)

Sample 1D: tensor([6, 3, 1, 1, 1, 3, 5, 6, 2, 1, 6, 3, 1, 3, 3])


In [ ]:
# 產生浮點數亂數樣本點
sample_2D = torch.rand(2, 3)
print("Sample 2D:", sample_2D)

Sample 2D: tensor([[0.3773, 0.2761, 0.2155],
        [0.0139, 0.8096, 0.6295]])


In [ ]:
# 產生標準常態分佈樣本點
sample_2D = torch.randn(3, 5)
print("Sample 2D:", sample_2D)

Sample 2D: tensor([[-1.3929, -0.5067,  0.9385, -0.7516, -0.6098],
        [-0.8092, -0.2053,  1.6095,  1.0559, -0.8898],
        [ 0.7238,  0.7493,  0.7503,  0.4933, -0.8137]])


In [ ]:
# 產生平均為 10, 標準差為 2 的常態分佈樣本點
sample_2D = torch.normal(10.0, 2.0, size=(3, 5))
print("Sample 2D:", sample_2D)

Sample 2D: tensor([[ 9.1941,  9.2001,  9.5628, 11.1922,  8.4743],
        [11.5496, 11.9238,  6.5907,  9.2942, 10.6185],
        [ 8.3128, 10.0341,  7.4853,  5.8675, 10.2180]])


# 張量基本運算

## 負數與加減乘除

In [ ]:
# 負數與加減
X1 = torch.tensor([1, 2, 3])
X2 = torch.tensor([20, 36, 40])

print(torch.neg(X1))
print(torch.add(X1, X2))
print(torch.sub(X1, X2))

tensor([-1, -2, -3])
tensor([21, 38, 43])
tensor([-19, -34, -37])


In [ ]:
# 張量的各種相乘
X1 = torch.tensor([1, 2, 3])
X2 = torch.tensor([20, 36, 40])

print(torch.mul(X1, X2))
print(torch.matmul(X1, X2))
print(torch.dot(X1, X2))
print(torch.inner(X1, X2))
print(torch.cross(X1, X2))
print(torch.outer(X1, X2))

tensor([ 20,  72, 120])
tensor(212)
tensor(212)
tensor(212)
tensor([-28,  20,  -4])
tensor([[ 20,  36,  40],
        [ 40,  72,  80],
        [ 60, 108, 120]])


In [ ]:
# 張量的各種相除
X1 = torch.tensor([1, 2, 3])
X2 = torch.tensor([20, 36, 40])

print(torch.reciprocal(X1))
print(torch.div(X1, X2))
print(torch.remainder(X1, X2))

X = torch.Tensor([[1, 2], [3, 4]])
Y = torch.inverse(X)
print(torch.matmul(X, Y))

tensor([1.0000, 0.5000, 0.3333])
tensor([0.0500, 0.0556, 0.0750])
tensor([1, 2, 3])
tensor([[1., 0.],
        [0., 1.]])


## 切片運算

In [ ]:
# 一維張量切片運算
slice_1D = torch.randint(20, size=(20,))

print(slice_1D)
print(slice_1D[:5])

tensor([19, 14,  0, 10,  6, 13, 16, 12,  1, 17, 16,  2,  7, 18, 13, 19, 19, 16,
         1,  5])
tensor([19, 14,  0, 10,  6])


In [ ]:
# 二維張量切片運算
slice_2D = torch.randint(20, size=(5, 5))

print(slice_2D)
print(slice_2D[:3, :3])

tensor([[16, 14,  4,  0, 11],
        [19, 15,  2,  5,  1],
        [12, 17,  1, 16, 12],
        [ 5,  2,  8,  5, 15],
        [15, 19,  9, 11, 19]])
tensor([[16, 14,  4],
        [19, 15,  2],
        [12, 17,  1]])


## 維度壓縮與擴張

In [ ]:
# 維度壓縮
sample_2D = torch.tensor([[1, 2, 3]])

print("Dimension:", sample_2D.size())
print(sample_2D)

sample_1D = sample_2D.squeeze()
print("Dimension:", sample_1D.size())
print(sample_1D)

Dimension: torch.Size([1, 3])
tensor([[1, 2, 3]])
Dimension: torch.Size([3])
tensor([1, 2, 3])


In [ ]:
# 維度擴張
sample_1D = torch.tensor([1, 2, 3])

print("Dimension:", sample_1D.size())
print(sample_1D)

sample_2D = sample_1D.unsqueeze(0)
print("Dimension:", sample_2D.size())
print(sample_2D)

Dimension: torch.Size([3])
tensor([1, 2, 3])
Dimension: torch.Size([1, 3])
tensor([[1, 2, 3]])


## 張量合併與分割

In [ ]:
# 張量合併
X1 = torch.tensor([[1, 2], [3, 4]])
X2 = torch.tensor([[5, 6], [7, 8]])

# 以列為邊界
print(torch.cat((X1, X2), dim=0))

# 以行為邊界
print(torch.cat((X1, X2), dim=1))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [ ]:
# 張量分割
X = torch.tensor([[1, 2], [3, 4]])

# 以列為邊界
print(torch.unbind(X, dim=0))

# 以行為邊界
print(torch.unbind(X, dim=1))

(tensor([1, 2]), tensor([3, 4]))
(tensor([1, 3]), tensor([2, 4]))


## 張量轉置

In [ ]:
# 將兩個張量合併、改維度、再轉置
X1 = torch.tensor([1, 2, 3])
X2 = torch.tensor([20, 36, 40])

features = torch.cat((X1, X2)).view(2, 3).T
print(features)

tensor([[ 1, 20],
        [ 2, 36],
        [ 3, 40]])


## 常用函數

In [ ]:
# 小數捨入
num1 = torch.tensor([-1.67, -1.01, -0.35, 0.97, 1.63])
print(num1)

print(torch.round(num1, decimals=1))
print(torch.floor(num1))
print(torch.ceil(num1))

tensor([-1.6700, -1.0100, -0.3500,  0.9700,  1.6300])
tensor([-1.7000, -1.0000, -0.4000,  1.0000,  1.6000])
tensor([-2., -2., -1.,  0.,  1.])
tensor([-1., -1., -0.,  1.,  2.])


In [ ]:
# 指數相關函數
X1 = torch.arange(1.0, 10.0, 1.0).view(3, 3)
print(X1)

print(torch.pow(X1, X1))
print(torch.exp2(X1))
print(torch.exp(X1))
print(torch.sqrt(X1))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1.0000e+00, 4.0000e+00, 2.7000e+01],
        [2.5600e+02, 3.1250e+03, 4.6656e+04],
        [8.2354e+05, 1.6777e+07, 3.8742e+08]])
tensor([[  2.,   4.,   8.],
        [ 16.,  32.,  64.],
        [128., 256., 512.]])
tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02],
        [1.0966e+03, 2.9810e+03, 8.1031e+03]])
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000]])


In [ ]:
# 對數相關函數
X1 = torch.arange(2, 20, 2).view(3, 3)
print(X1)

print(torch.log10(X1))
print(torch.log2(X1))
print(torch.log(X1))

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
tensor([[0.3010, 0.6021, 0.7782],
        [0.9031, 1.0000, 1.0792],
        [1.1461, 1.2041, 1.2553]])
tensor([[1.0000, 2.0000, 2.5850],
        [3.0000, 3.3219, 3.5850],
        [3.8074, 4.0000, 4.1699]])
tensor([[0.6931, 1.3863, 1.7918],
        [2.0794, 2.3026, 2.4849],
        [2.6391, 2.7726, 2.8904]])


In [ ]:
# 三角函數
deg = torch.tensor([0, 30, 60, 90])
rad = torch.deg2rad(deg)
print(torch.rad2deg(rad))

print(torch.sin(rad))
print(torch.cos(rad))
print(torch.tan(rad))

tensor([ 0.0000, 30.0000, 60.0000, 90.0000])
tensor([0.0000, 0.5000, 0.8660, 1.0000])
tensor([ 1.0000e+00,  8.6603e-01,  5.0000e-01, -4.3711e-08])
tensor([ 0.0000e+00,  5.7735e-01,  1.7321e+00, -2.2877e+07])


In [ ]:
# 統計量的計算
stat1 = torch.arange(1.0, 11.0)
print(stat1)

print(stat1.min())
print(stat1.max())
print(stat1.sum())
print(stat1.mean())
print(stat1.median())
print(stat1.std())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor(1.)
tensor(10.)
tensor(55.)
tensor(5.5000)
tensor(5.)
tensor(3.0277)
