In [ ]:
import keras

In [ ]:
print(keras.__version__)

2.13.1


In [ ]:
x =10
print(x)

10


In [ ]:
pip list | grep keras

keras                            2.13.1


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Array

In [ ]:
ary1dim = np.array([1, 0, 0, 2, 5])
ary2dim = np.array([[1, 0, 2], [2, 4, 9]])
ary3_diff = np.array([199, 'apple', 'True'])
print(ary1dim)
print(ary2dim)
print(ary3_diff)

[1 0 0 2 5]
[[1 0 2]
 [2 4 9]]
['199' 'apple' 'True']


Special Array

In [ ]:
ary_O = np.zeros([3,])
ary_1 = np.zeros([3,1])
print(ary_O)
print(ary_1)

[0. 0. 0.]
[[0.]
 [0.]
 [0.]]


In [ ]:
ary_id0 = np.eye(1)
ary_id1 = np.eye(2)
print(ary_id0)
print(ary_id1)

[[1.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
ary_ones_1 = np.ones([4])
ary_ones0 = np.ones([4, ])
ary_ones1 = np.ones([4, 1])
ary_ones2 = np.ones([4, 2])
ary_ones3 = np.ones([4, 3])

print(ary_ones_1)
print(ary_ones0)
print(ary_ones1)
print(ary_ones2)
print(ary_ones3)

[1. 1. 1. 1.]
[1. 1. 1. 1.]
[[1.]
 [1.]
 [1.]
 [1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
ary_const_1 = np.full(3, 7)
ary_const0 = np.full((3, ), 7)
ary_const1 = np.full((3, 1), 7)
ary_const2 = np.full((3, 2), 7)

print(ary_const_1)
print(ary_const0)
print(ary_const1)
print(ary_const2)

[7 7 7]
[7 7 7]
[[7]
 [7]
 [7]]
[[7 7]
 [7 7]
 [7 7]]


In [ ]:
ary0 = np.array([[2, 3, 4],
                 [5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])
print(ary0[1, -1], ary0[3, 2])
print(ary0.ndim)
print(ary0.shape)

7 13
2
(5, 3)


# 產生樣本點

產生線性樣本點

In [ ]:
sample1 = np.arange(0., 5., 0.2)
sample2 = sample1.copy()
np.random.shuffle(sample2)
sample3 = sample1.reshape(5, 5)
sample4 = sample1.reshape(25)
# 將元素型態改為「文字」，並將之印出
sample5 = sample1.astype('unicode')

print(sample1, '\n')
print(sample2)
print(sample3)
print(sample4)
print(sample5)
# 因為電腦有誤差, 十進位的有限小數轉成二進位時會變成無限小數再因為電腦記憶體有限會被截斷, 所以小數不叫小數, 叫浮點數.

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8] 

[2.  1.2 3.8 3.4 1.4 3.2 4.8 0.4 4.2 0.6 3.  2.4 2.2 2.6 4.4 1.  0.8 1.6
 2.8 4.6 0.2 4.  3.6 0.  1.8]
[[0.  0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8]
 [3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8]]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]
['0.0' '0.2' '0.4' '0.6000000000000001' '0.8' '1.0' '1.2000000000000002'
 '1.4000000000000001' '1.6' '1.8' '2.0' '2.2' '2.4000000000000004' '2.6'
 '2.8000000000000003' '3.0' '3.2' '3.4000000000000004' '3.6'
 '3.8000000000000003' '4.0' '4.2' '4.4' '4.6000000000000005'
 '4.800000000000001']


產生「等差」樣本點 \
產生「等比」樣本點

In [ ]:
sample1_1 = np.linspace(0., 5., 15)
sample1_2 = np.logspace(0., 5., 15)

print(sample1_1)
print(sample1_2)

[0.         0.35714286 0.71428571 1.07142857 1.42857143 1.78571429
 2.14285714 2.5        2.85714286 3.21428571 3.57142857 3.92857143
 4.28571429 4.64285714 5.        ]
[1.00000000e+00 2.27584593e+00 5.17947468e+00 1.17876863e+01
 2.68269580e+01 6.10540230e+01 1.38949549e+02 3.16227766e+02
 7.19685673e+02 1.63789371e+03 3.72759372e+03 8.48342898e+03
 1.93069773e+04 4.39397056e+04 1.00000000e+05]


產生「整數亂數」樣本點 \
產生「浮點數數亂數」樣本點

In [ ]:
sample2_1 = np.random.randint(0, 10, 100) # 0~10 choose 100 integer
sample2_2 = np.random.rand(2, 10) # 產生 [0, 1) 之間的浮點亂數 2x10 個 （其它範圍亂數：以 r [0, 1) + b 製作之）
sample2_3 = 3*np.random.rand(2, 10) + (-2) # 產生 [-2, 1) 之間的浮點亂數 2x10 個

print(sample2_1)
print(sample2_2)
print(sample2_3)

[5 6 4 0 5 3 9 0 7 1 3 7 0 7 6 2 6 3 3 5 6 8 4 1 2 1 9 3 0 4 1 2 9 2 4 6 4
 3 0 2 3 6 7 9 3 1 8 0 2 6 5 2 1 3 3 4 3 6 4 0 0 7 1 1 1 1 9 3 6 2 9 0 6 7
 1 8 0 7 9 2 2 9 3 9 6 4 5 0 9 5 1 5 9 6 8 7 6 6 6 5]
[[0.49597498 0.35080359 0.68298058 0.79836293 0.9556483  0.36265961
  0.68926893 0.86403159 0.28589274 0.98901538]
 [0.66528506 0.20404564 0.15933265 0.60153991 0.27161796 0.89911866
  0.76234075 0.37423621 0.63778295 0.97188678]]
[[-1.17832857  0.85066317 -1.85031633  0.9440591  -0.11216648 -0.15927043
  -1.44186989 -0.02259888 -0.37109806 -0.77546394]
 [ 0.49541608 -1.47533362 -0.61286974 -1.61706889  0.25903338 -1.5811554
   0.81907611 -0.30571623 -0.06820959 -0.69556693]]


產生「標準常態分佈N(0, 1)」樣本點 \
產生「⼀般常態分佈」樣本點

In [ ]:
sample3_1 = np.random.randn(3, 5)
sample3_2 = np.random.normal(10, 2, size = (3, 5))

print(sample3_1)
print(sample3_2)

[[ 1.43250307e+00 -1.02791775e-01  9.84457866e-01 -8.12444813e-01
   1.19809923e+00]
 [-3.35425338e-01 -3.38641401e-04  7.91739392e-01  5.35615818e-01
  -6.30010851e-01]
 [ 1.07166090e+00  1.49255252e-01  5.42261452e-01 -3.39780281e-01
  -4.20826786e-01]]
[[12.10802313 15.66098274  9.59755131  7.67063756  5.2431375 ]
 [ 9.01861129 12.09640839  7.74807135  8.94183163 11.01160499]
 [12.0672326   7.94584412 11.74598831 11.00784836 12.67451999]]


切片運算(Slicing)

In [ ]:
# 1-dim
slice1 = np.random.randint(4, size = 20)

print(slice1)
print(slice1[:5])

# 2-dim
slice2 = np.random.randint(4, size = (3, 5))

print(slice2)
print(slice2[:3, :3])

[2 1 2 3 1 0 2 1 3 1 1 3 1 0 0 1 1 1 3 0]
[2 1 2 3 1]
[[3 0 2 3 2]
 [1 1 0 2 1]
 [0 1 3 3 3]]
[[3 0 2]
 [1 1 0]
 [0 1 3]]


統計樣本資訊.

In [ ]:
stat1 = np.arange(0, 100)

print(stat1)

print(stat1.min())
print(stat1.max())
print(stat1.sum())
print(stat1.mean())
print(stat1.std())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
0
99
4950
49.5
28.86607004772212


In [ ]:
sample4_1 = np.array([1, 2, 3, 4])
sample4_2 = np.array([5, 6, 7, 8])
sample4_3 = np.concatenate((sample4_1, sample4_2))
sample4_4 = np.concatenate((sample4_2, sample4_1))
sample4_5 = np.concatenate((sample4_2, sample4_1)).reshape(2, 4)
sample4_6 = np.concatenate((sample4_2, sample4_1)).reshape(2, 4).T

print(sample4_1)
print(sample4_2)
print(sample4_3)
print(sample4_4)
print(sample4_5)
print(sample4_6)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]
[5 6 7 8 1 2 3 4]
[[5 6 7 8]
 [1 2 3 4]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]]
