In [4]:
import numpy as np
import pandas as pd

In [23]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/人工智慧程式設計/Homework/HealthCheck.csv')
print(dataset)

      Race  Height_cm  Weight_kg Over70yr
0    White      186.0       90.0      Yes
1  African      185.0       98.0       No
2    Asian      175.0       80.0       No
3  African      170.0       75.0      Yes
4    Asian      164.0        NaN       No
5    Asian      170.0       72.0      Yes
6    White      178.0       75.0       No
7    White        NaN       89.0      Yes
8  African      165.0       79.0      Yes


檢查是否有缺失資料, 再算每列有幾個, 再看看整個dataframe總共有幾個缺失資料

In [24]:
sum(dataset.isnull().sum())

2

切分自變數、應變數

In [30]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, 3].values

In [31]:
X, Y

(array([['White', 186.0, 90.0],
        ['African', 185.0, 98.0],
        ['Asian', 175.0, 80.0],
        ['African', 170.0, 75.0],
        ['Asian', 164.0, nan],
        ['Asian', 170.0, 72.0],
        ['White', 178.0, 75.0],
        ['White', nan, 89.0],
        ['African', 165.0, 79.0]], dtype=object),
 array(['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes'],
       dtype=object))

處理缺失資料

In [34]:
from sklearn.impute import SimpleImputer
# 先做 Height_cm

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') # 將NaN值用平均值代替.
imputer = imputer.fit(X[:, 1:2])
X[:, 1:2] = imputer.transform(X[:, 1:2])

# 再做 Weight_cm

imputer = SimpleImputer(missing_values = np.nan, strategy = 'median') # 將NaN值用平均值代替.
imputer = imputer.fit(X[:, 2:3])
X[:, 2:3] = imputer.transform(X[:, 2:3])

In [35]:
X

array([['White', 186.0, 90.0],
       ['African', 185.0, 98.0],
       ['Asian', 175.0, 80.0],
       ['African', 170.0, 75.0],
       ['Asian', 164.0, 82.25],
       ['Asian', 170.0, 72.0],
       ['White', 178.0, 75.0],
       ['White', 174.125, 89.0],
       ['African', 165.0, 79.0]], dtype=object)

類別資料數位化.

In [36]:
# 使用標籤編碼器，將應變數 Y 數位化
from sklearn.preprocessing import LabelEncoder

labelEncoder = LabelEncoder()
Y = labelEncoder.fit_transform(Y).astype("float64")

In [37]:
print(Y)

[1. 0. 0. 1. 0. 1. 0. 1. 1.]


In [38]:
# 使用獨熱編碼器(one-hot encoding)，將自變數 X 數位化
ary_dummies = pd.get_dummies(X[:, 0]).values
X = np.concatenate((ary_dummies, X[:, 1:3]), axis=1).astype("float64")

In [39]:
print(X)

[[  0.      0.      1.    186.     90.   ]
 [  1.      0.      0.    185.     98.   ]
 [  0.      1.      0.    175.     80.   ]
 [  1.      0.      0.    170.     75.   ]
 [  0.      1.      0.    164.     82.25 ]
 [  0.      1.      0.    170.     72.   ]
 [  0.      0.      1.    178.     75.   ]
 [  0.      0.      1.    174.125  89.   ]
 [  1.      0.      0.    165.     79.   ]]


切割訓練集和測試集

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [41]:
X_train, X_test, Y_train, Y_test

(array([[  1.  ,   0.  ,   0.  , 185.  ,  98.  ],
        [  0.  ,   1.  ,   0.  , 164.  ,  82.25],
        [  1.  ,   0.  ,   0.  , 165.  ,  79.  ],
        [  0.  ,   0.  ,   1.  , 178.  ,  75.  ],
        [  1.  ,   0.  ,   0.  , 170.  ,  75.  ],
        [  0.  ,   0.  ,   1.  , 186.  ,  90.  ],
        [  0.  ,   1.  ,   0.  , 170.  ,  72.  ]]),
 array([[  0.   ,   0.   ,   1.   , 174.125,  89.   ],
        [  0.   ,   1.   ,   0.   , 175.   ,  80.   ]]),
 array([0., 0., 1., 0., 1., 1., 1.]),
 array([1., 0.]))

特徵縮放

In [42]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler().fit(X_train)
X_train = sc_X.transform(X_train)
X_test = sc_X.transform(X_test)

Result

In [44]:
X_train, X_test, Y_train, Y_test

(array([[ 1.15470054, -0.63245553, -0.63245553,  1.30941777,  1.89111602],
        [-0.8660254 ,  1.58113883, -0.63245553, -1.19037979,  0.07416141],
        [ 1.15470054, -0.63245553, -0.63245553, -1.07134181, -0.30076573],
        [-0.8660254 , -0.63245553,  1.58113883,  0.47615192, -0.76221452],
        [ 1.15470054, -0.63245553, -0.63245553, -0.47615192, -0.76221452],
        [-0.8660254 , -0.63245553,  1.58113883,  1.42845575,  0.96821844],
        [-0.8660254 ,  1.58113883, -0.63245553, -0.47615192, -1.10830111]]),
 array([[-0.8660254 , -0.63245553,  1.58113883,  0.01487975,  0.85285625],
        [-0.8660254 ,  1.58113883, -0.63245553,  0.11903798, -0.18540353]]),
 array([0., 0., 1., 0., 1., 1., 1.]),
 array([1., 0.]))