In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/cnchi/datasets/master/Match_Making.csv')

In [ ]:
df

ID  Age  Height  Salary Education Matching
0   ID0001   25     179      75   College        N
1   ID0002   33     190      95   College        Y
2   ID0003   28     180      90    Master        Y
3   ID0004   25     178      90    Master        Y
4   ID0005   46     177     500    Master        N
5   ID0006   40     170     350  Bachelor        N
6   ID0007   34     174     100    Master        Y
7   ID0008   36     181     220  Bachelor        N
8   ID0009   35     170     125    Master        Y
9   ID0010   30     180     175  Bachelor        Y
10  ID0011   28     174     150  Bachelor        N
11  ID0012   29     176     180  Bachelor        Y

題目要求：

1. 請讀入該資料集，並且將之印出（一分）。
2. 請切分自變數 X 與應變數 Y。其中應變數 Y 對應的欄位為 Matching。切分時，請把把 ID 這個欄位去除。最後把自變數 X 與應變數 Y 印出（三分）。
3. 請針對 Education 與 Matching 這兩個欄位，執行類別資料數位化。執行完畢後，請再將整個自變數 X 與應變數 Y 印出（兩分）。
4. 請切分出 X_train, X_test, Y_train, Y_test 之後印出（兩分）。
5. 請針對 X_train 與 X_test 執行特徵縮放後印出（兩分）。

## 檢查是否有缺失資料, 再算每列有幾個, 再看看整個dataframe總共有幾個缺失資料

In [ ]:
sum(df.isnull().sum())

0

## 切分自變數、應變數

In [ ]:
X = df.iloc[:, 1:-1].values
Y = df.iloc[:, -1].values

In [ ]:
X, Y

(array([[25, 179, 75, 'College'],
        [33, 190, 95, 'College'],
        [28, 180, 90, 'Master'],
        [25, 178, 90, 'Master'],
        [46, 177, 500, 'Master'],
        [40, 170, 350, 'Bachelor'],
        [34, 174, 100, 'Master'],
        [36, 181, 220, 'Bachelor'],
        [35, 170, 125, 'Master'],
        [30, 180, 175, 'Bachelor'],
        [28, 174, 150, 'Bachelor'],
        [29, 176, 180, 'Bachelor']], dtype=object),
 array(['N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y'],
       dtype=object))

## 類別資料數位化.

### Education

In [ ]:
import numpy as np
# 使用獨熱編碼器(one-hot encoding)，將自變數 X 數位化
ary_dummies = pd.get_dummies(X[:, 3]).values
X = np.concatenate((ary_dummies, X[:, 0:2]), axis=1).astype("float64")

In [ ]:
print(X)

[[  0.   1.   0.  25. 179.]
 [  0.   1.   0.  33. 190.]
 [  0.   0.   1.  28. 180.]
 [  0.   0.   1.  25. 178.]
 [  0.   0.   1.  46. 177.]
 [  1.   0.   0.  40. 170.]
 [  0.   0.   1.  34. 174.]
 [  1.   0.   0.  36. 181.]
 [  0.   0.   1.  35. 170.]
 [  1.   0.   0.  30. 180.]
 [  1.   0.   0.  28. 174.]
 [  1.   0.   0.  29. 176.]]


### Matching

In [ ]:
# 使用標籤編碼器，將應變數 Y 數位化
from sklearn.preprocessing import LabelEncoder

labelEncoder = LabelEncoder()
Y = labelEncoder.fit_transform(Y).astype("float64")

In [ ]:
print(Y)

[0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1.]


## 切割訓練集和測試集

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
X_train, X_test, Y_train, Y_test

(array([[  1.,   0.,   0.,  28., 174.],
        [  0.,   0.,   1.,  28., 180.],
        [  0.,   0.,   1.,  35., 170.],
        [  0.,   1.,   0.,  33., 190.],
        [  1.,   0.,   0.,  36., 181.],
        [  1.,   0.,   0.,  30., 180.],
        [  0.,   0.,   1.,  25., 178.],
        [  0.,   1.,   0.,  25., 179.],
        [  1.,   0.,   0.,  40., 170.]]),
 array([[  0.,   0.,   1.,  34., 174.],
        [  1.,   0.,   0.,  29., 176.],
        [  0.,   0.,   1.,  46., 177.]]),
 array([0., 1., 1., 1., 0., 1., 1., 0., 0.]),
 array([1., 1., 0.]))

## 特徵縮放

In [ ]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler().fit(X_train)
X_train = sc_X.transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
X_train, X_test

(array([[ 1.11803399, -0.53452248, -0.70710678, -0.63375022, -0.68599434],
        [-0.89442719, -0.53452248,  1.41421356, -0.63375022,  0.34299717],
        [-0.89442719, -0.53452248,  1.41421356,  0.79218778, -1.37198868],
        [-0.89442719,  1.87082869, -0.70710678,  0.38477692,  2.05798302],
        [ 1.11803399, -0.53452248, -0.70710678,  0.99589321,  0.51449576],
        [ 1.11803399, -0.53452248, -0.70710678, -0.22633937,  0.34299717],
        [-0.89442719, -0.53452248,  1.41421356, -1.24486651,  0.        ],
        [-0.89442719,  1.87082869, -0.70710678, -1.24486651,  0.17149859],
        [ 1.11803399, -0.53452248, -0.70710678,  1.81071492, -1.37198868]]),
 array([[-0.89442719, -0.53452248,  1.41421356,  0.58848235, -0.68599434],
        [ 1.11803399, -0.53452248, -0.70710678, -0.43004479, -0.34299717],
        [-0.89442719, -0.53452248,  1.41421356,  3.03294749, -0.17149859]]))